CREATE TABLE [Covid].[DataByCounty](
	[DataByCountyID] [INT] IDENTITY(1,1) NOT NULL,
	[Date] [DATE] NOT NULL,
	[County] [NVARCHAR](60) NOT NULL,
	[State] [NVARCHAR](60) NOT NULL,
	[FIPS] [INT] NULL,
	[Cases] [INT] NOT NULL,
	[Deaths] [INT] NULL,
	[UpdatedOnUtc] [DATETIMEOFFSET](7) NOT NULL,
	[CreatedOnUtc] [DATETIMEOFFSET](7) NOT NULL
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_DataByCounty_Date_County_State] ON [Covid].[DataByCounty]
(
	[Date] ASC,
	[County] ASC,
	[State] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
