name: Web App Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - covid-api
    paths:
      - 'Source/CovidAndWeatherVisualization/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Source/CovidAndWeatherVisualization/**'
env:
  AZURE_WEBAPP_NAME: covid-weather-visualization    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './Source/CovidAndWeatherVisualization/CovidAndWeatherVisualization'      # set this to the path to your web app project, defaults to the repository root
  CLIENT_APP_PATH: './Source/CovidAndWeatherVisualization/CovidAndWeatherVisualization/ClientApp'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: NPM Install
        working-directory: ${{ env.CLIENT_APP_PATH }}
        run: npm ci

      - name: NPM Lint
        working-directory: ${{ env.CLIENT_APP_PATH }}
        run: npm run lint

      - name: NPM Test
        working-directory: ${{ env.CLIENT_APP_PATH }}
        run: npm run test

      # Run dotnet build and publish
      - name: dotnet/NPM build and publish
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './publishOutput' 
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publishOutput'